/************************************************************************
 * COMPUTE.H  -  Rechenoperationen fuer das Projekt Diplom
 *
 * (c) Wolfgang Lauffher
 *
 * Mai 1994
 ************************************************************************/

#include "types.h"

int Compute(void);
int Enumerate(void);
void Modifiziere_Werte(void);
void einfaerben(Loesungszeiger);
void Considering(void);


