/************************************************************************
 *
 * INIT.H  -  Init-Prozeduren fuer das Projekt Diplom
 *
 * (c) Wolfgang Lauffher
 *
 * Mai 1994
 ************************************************************************/

#include "menu.h"				// IDD_******* reinlutschen

#define INIT_ALGORITHMUS      	IDD_LOCAL
#define INIT_NACHBARSCHAFT	 	IDD_NACHBARnaechster
#define INIT_CLUSTERANZ         3
#define INIT_ANZAHLSUBS			0
#define INIT_NACHBARANZ			5
#define INIT_TABUFAKTOR			1.1
#define INIT_TABULISTENLAENGE	5

#define INIT_ANZGR				2
#define INIT_WHICHGR0			0
#define INIT_WHICHGR1			1
#define INIT_WHICHGR2			2

#define INIT_WICHTUNG0			1
#define INIT_WICHTUNG1			0
#define INIT_WICHTUNG2			0
#define INIT_WICHTUNG3          0
#define INIT_WICHTUNG4          0
#define INIT_WICHTUNG5          0

void Init (void);

