/**********************************************************
 * MENU.H  -  Konstanten fuer Callbacks
 *
 * Wolfgang Lauffher
 *
 * August 1994
 **********************************************************/

#include "diplom.h"			// Defines fuer Help-Tool

/* Menu */          
#define IDM_OPEN			1
#define IDM_PRINT			2
#define IDM_CLIP			3
#define IDM_END				4
#define IDM_AUSCLUSTER		11
#define IDM_AUSWERTE    	12
#define IDM_KKREUZ			13
#define IDM_LOESCHEN		14
#define IDM_COMPUTE 		21
#define IDM_ENUMERATE		22
#define IDM_WERTE			23
#define IDM_OPTIONEN		24
#define IDM_ABOUT			31
#define IDM_INHALT			32
#define IDM_TASTEN			33
#define IDM_HELP			35

/* Dialog Optionen */
#define IDD_CLUSTER			41
#define IDD_WICHTUNG		42
#define IDD_OPTIONENHELP	43

#define IDD_NACHBARanz		45
#define IDD_TABUliste		46
#define IDD_TABUfaktor		47

#define IDD_LOCAL			51
#define IDD_ITERATIVE		52
#define IDD_SIMAN			53
#define IDD_SIMANLOCAL		54
#define IDD_THRESHOLD		55
#define IDD_COMBINED		56
#define IDD_TABU			57

#define IDD_NACHBARnaechster	61
#define IDD_NACHBARcentroid		62
#define IDD_NACHBARrandom		63
#define IDD_SIMULTANEOUS        64

#define IDD_TEXTLISTE		66
#define IDD_TEXTFAKTOR		67
#define IDD_TEXTNACHBAR		68

/* Dialog Werte */
#define IDD_LISTEGR1		71
#define IDD_LISTEGR2		72
#define IDD_LISTEGR3		73
#define IDD_LISTECO1		74
#define IDD_LISTECO2		75
#define IDD_LISTECO3		76
#define IDD_LISTECO			77
#define IDD_WERTETAKE		78
#define IDD_WERTEHELP		79
#define IDD_WERTERESET		80
#define IDD_SPECIAL			81
#define IDD_SUBBEREICHE     82

/* Dialog Ausgabe */
#define IDD_BROWSE			84
#define IDD_SWAP			85
#define IDD_HILFE 			86

/* Dialog Wichtung */
#define IDD_WSS				91
#define IDD_WSS2			92
#define IDD_WSNS			93
#define IDD_WmaxS			94
#define IDD_WSmax			95
#define IDD_Wmaxmax			96
#define IDD_WICHTUNGHELP	97

/* Dialog Subbereiche */
#define IDD_MERKMAL			87
#define IDD_SUBMERKMAL		88
#define IDD_PFEIL			89
#define IDD_BITMAPPFEIL		1123	//VGA-OFFSET!
#define IDD_SUBHELP			90
